# Generated by Django 3.1.7 on 2021-03-17 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('part_number', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('ipc_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('ordered_by', models.CharField(choices=[('Terence', 'Terence'), ('James', 'James'), ('Denten', 'Denten'), ('Ivin', 'Ivin')], default='', max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('serial_off', models.CharField(blank=True, max_length=50, null=True)),
                ('serial_on', models.CharField(blank=True, max_length=50, null=True)),
                ('recieved', models.DateTimeField(auto_now=True)),
                ('tail_number', models.CharField(choices=[('Stock', 'Stock'), ('N192WW', 'N192WW'), ('N193WW', 'N193WW'), ('N194WW', 'N194WW'), ('N195WW', 'N195WW'), ('N196WW', 'N196WW'), ('N197WW', 'N197WW'), ('N198WW', 'N198WW'), ('N190WW', 'N190WW'), ('N906WW', 'N906WW'), ('N3830S', 'N3830S'), ('N323WW', 'N323WW'), ('N491AK', 'N491AK'), ('N492AK', 'N492AK'), ('N725WW', 'N725WW'), ('N789WW', 'N789WW'), ('N921WW', 'N921WW')], default='AirFrame', max_length=20)),
                ('part_type', models.CharField(choices=[('Rotable', 'Rotable'), ('Tires', 'Tires'), ('AGS', 'AGS'), ('Shelflife', 'Shelflife')], default='Rotable', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ToolChecker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_type', models.IntegerField(choices=[(0, 'Calibrated'), (1, 'Un-Calibrated')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_number', models.CharField(choices=[('N192WW', 'N192WW'), ('N193WW', 'N193WW'), ('N194WW', 'N194WW'), ('N195WW', 'N195WW'), ('N196WW', 'N196WW'), ('N197WW', 'N197WW'), ('N198WW', 'N198WW'), ('N190WW', 'N190WW'), ('N906WW', 'N906WW'), ('N3830S', 'N3830S'), ('N323WW', 'N323WW'), ('N491AK', 'N491AK'), ('N492AK', 'N492AK'), ('N725WW', 'N725WW'), ('N789WW', 'N789WW'), ('N921WW', 'N921WW')], default='AirFrame', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('COMPLETED', 'COMPLETED')], default='OPEN', max_length=20)),
                ('type_airframe', models.CharField(blank=True, max_length=50, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('ldgs_at_open', models.IntegerField(blank=True, default='0', null=True)),
                ('workorder_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tools_UnCalibrated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('part_number', models.CharField(blank=True, max_length=50, null=True)),
                ('recieved', models.DateTimeField(auto_now=True)),
                ('issued', models.BooleanField(blank=True, default='False', null=True)),
                ('workorder_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mgmt.workorders')),
            ],
        ),
        migrations.CreateModel(
            name='Tools_Calibrated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('part_number', models.CharField(blank=True, max_length=50, null=True)),
                ('recieved', models.DateTimeField(auto_now=True)),
                ('calibrated', models.BooleanField(blank=True, default='True', null=True)),
                ('calibrated_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('cert_no', models.CharField(blank=True, max_length=50, null=True)),
                ('range_no', models.CharField(blank=True, max_length=50, null=True)),
                ('issued', models.BooleanField(blank=True, default='False', null=True)),
                ('workorder_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mgmt.workorders')),
            ],
        ),
        migrations.CreateModel(
            name='StockfromShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(blank=True, max_length=50, null=True)),
                ('part_type', models.CharField(choices=[('Rotable', 'Rotable'), ('Tires', 'Tires'), ('AGS', 'AGS'), ('Shelflife', 'Shelflife')], default='Rotable', max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('reserved_for', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_order_number', models.CharField(blank=True, max_length=50, null=True)),
                ('receive_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('shelflife', models.IntegerField(blank=True, default='0', null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('minimum_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('bin_number', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('issue_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_to', models.CharField(blank=True, max_length=50, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('export_to_CSV', models.BooleanField(default=False)),
                ('workorders', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mgmt.workorders')),
            ],
        ),
    ]
