# Generated by Django 3.1.7 on 2021-06-24 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill', models.CharField(blank=True, max_length=50, null=True)),
                ('urlWayBill', models.URLField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('part_number', models.CharField(blank=True, max_length=50, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('jobCardNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('Historical', models.BooleanField(blank=True, default='False', null=True)),
                ('batch_no', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('receive_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('order_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('issue_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('ipc_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('date_ordered', models.DateTimeField(auto_now=True)),
                ('date_received', models.DateTimeField(blank=True, null=True)),
                ('ticketed', models.BooleanField(blank=True, default='False', null=True)),
                ('recieve_part', models.BooleanField(default='False')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('vendor', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_order_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='PurchaseOrder #')),
                ('Repaired', models.BooleanField(blank=True, default='False', null=True)),
                ('Quarentine', models.BooleanField(blank=True, default='False', null=True)),
                ('exported', models.BooleanField(blank=True, default='False', null=True)),
                ('bin_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cert_document', models.ImageField(blank=True, null=True, upload_to='Cert-Parts', verbose_name='Certification Document')),
                ('SRN', models.CharField(blank=True, max_length=50, null=True)),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='barcode-Parts')),
                ('part_type', models.CharField(choices=[('Rotable', 'Rotable'), ('Tires', 'Tires'), ('AGS', 'AGS'), ('Consumables', 'Consumables'), ('Shelf-life', 'Shelf-life')], default='Rotable', max_length=20, verbose_name='Part-Type')),
                ('condition', models.CharField(choices=[('NEW', 'NEW'), ('OH', 'OH'), ('AR', 'AR'), ('SV', 'SV'), ('REPAIRABLE', 'REPAIRABLE'), ('DAMAGED', 'DAMAGED'), ('INCORRECT-DOC', 'INCORRECT-DOC'), ('WRONG-PART', 'WRONG-PART')], default='NEW', max_length=20)),
                ('repaired_by', models.CharField(choices=[('INHOUSE', 'INHOUSE'), ('SHOP', 'SHOP')], default='', max_length=20)),
                ('inspector', models.ForeignKey(blank=True, default='--', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspector', to='mgmt.employees', verbose_name='Inspector:')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_by', to='mgmt.employees', verbose_name='Issued by:')),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_by', to='mgmt.employees', verbose_name='Ordered by:')),
            ],
        ),
        migrations.CreateModel(
            name='TailNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToolChecker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_type', models.IntegerField(choices=[(0, 'Calibrated'), (1, 'Un-Calibrated')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_number', models.CharField(choices=[('N192WW', 'N192WW'), ('N193WW', 'N193WW'), ('N194WW', 'N194WW'), ('N195WW', 'N195WW'), ('N196WW', 'N196WW'), ('N197WW', 'N197WW'), ('N198WW', 'N198WW'), ('N190WW', 'N190WW'), ('N906WW', 'N906WW'), ('N3830S', 'N3830S'), ('N323WW', 'N323WW'), ('N491AK', 'N491AK'), ('N492AK', 'N492AK'), ('N725WW', 'N725WW'), ('N789WW', 'N789WW'), ('N921WW', 'N921WW')], default='AirFrame', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('COMPLETED', 'COMPLETED')], default='OPEN', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_airframe', models.CharField(blank=True, max_length=50, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('ldgs_at_open', models.IntegerField(blank=True, default='0', null=True)),
                ('hours_at_open', models.IntegerField(blank=True, default='0', null=True)),
                ('workorder_number', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tools_UnCalibrated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('part_number', models.CharField(blank=True, max_length=50, null=True)),
                ('recieved', models.DateTimeField(auto_now=True)),
                ('issued', models.BooleanField(blank=True, default='False', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workorder_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mgmt.workorders')),
            ],
        ),
        migrations.CreateModel(
            name='Tools_Calibrated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('part_number', models.CharField(blank=True, max_length=50, null=True)),
                ('recieved', models.DateTimeField(auto_now=True)),
                ('calibrated', models.BooleanField(blank=True, default='True', null=True)),
                ('calibrated_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('cert_no', models.CharField(blank=True, max_length=50, null=True)),
                ('calibration_certificate', models.ImageField(blank=True, null=True, upload_to='Cert-Tools', verbose_name='Certification Document')),
                ('range_no', models.CharField(blank=True, max_length=50, null=True)),
                ('issued', models.BooleanField(blank=True, default='False', null=True)),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='barcode-calibrated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workorder_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mgmt.workorders')),
            ],
        ),
        migrations.CreateModel(
            name='ReorderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(choices=[('Rotable', 'Rotable'), ('Tires', 'Tires'), ('AGS', 'AGS'), ('Consumables', 'Consumables'), ('Shelf-life', 'Shelf-life')], default='Rotable', max_length=20, verbose_name='Part-Type')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('part_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ipc_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('tail_number', models.CharField(choices=[('Stock', 'Stock'), ('N192WW', 'N192WW'), ('N193WW', 'N193WW'), ('N194WW', 'N194WW'), ('N195WW', 'N195WW'), ('N196WW', 'N196WW'), ('N197WW', 'N197WW'), ('N198WW', 'N198WW'), ('N190WW', 'N190WW'), ('N906WW', 'N906WW'), ('N3830S', 'N3830S'), ('N323WW', 'N323WW'), ('N491AK', 'N491AK'), ('N492AK', 'N492AK'), ('N725WW', 'N725WW'), ('N789WW', 'N789WW'), ('N921WW', 'N921WW')], default='AirFrame', max_length=20, verbose_name='Tail #')),
                ('ordered_by', models.CharField(choices=[('Terence', 'Terence'), ('James', 'James'), ('Denten', 'Denten'), ('Ivin', 'Ivin'), ('Ester', 'Ester')], default='', max_length=20, verbose_name='Ordered by:')),
                ('date_ordered', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('order_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartWorkOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('removed_from', models.CharField(blank=True, max_length=50, null=True)),
                ('removed_by', models.CharField(blank=True, max_length=50, null=True)),
                ('cert_document', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Certification Document')),
                ('jobCardNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('receivedRepair', models.BooleanField(blank=True, default='False', null=True)),
                ('issued_by', models.CharField(choices=[('Terence', 'Terence'), ('James', 'James'), ('Denten', 'Denten'), ('Ivin', 'Ivin')], default='', max_length=20, verbose_name='Issued by:')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mgmt.parts')),
                ('workorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mgmt.workorders')),
            ],
        ),
        migrations.AddField(
            model_name='parts',
            name='tail_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mgmt.tailnumber', verbose_name='Tail #'),
        ),
        migrations.AddField(
            model_name='parts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parts',
            name='workorders',
            field=models.ManyToManyField(null=True, related_name='parts', through='mgmt.PartWorkOrders', to='mgmt.WorkOrders'),
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('part_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_ordered', models.DateTimeField(auto_now=True)),
                ('order_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('ipc_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('vendor', models.CharField(blank=True, max_length=50, null=True)),
                ('ordered_by', models.CharField(choices=[('Terence', 'Terence'), ('James', 'James'), ('Denten', 'Denten'), ('Ivin', 'Ivin')], default='', max_length=20, verbose_name='Ordered by:')),
                ('tail_number', models.CharField(choices=[('Stock', 'Stock'), ('N192WW', 'N192WW'), ('N193WW', 'N193WW'), ('N194WW', 'N194WW'), ('N195WW', 'N195WW'), ('N196WW', 'N196WW'), ('N197WW', 'N197WW'), ('N198WW', 'N198WW'), ('N190WW', 'N190WW'), ('N906WW', 'N906WW'), ('N3830S', 'N3830S'), ('N323WW', 'N323WW'), ('N491AK', 'N491AK'), ('N492AK', 'N492AK'), ('N725WW', 'N725WW'), ('N789WW', 'N789WW'), ('N921WW', 'N921WW')], default='AirFrame', max_length=20, verbose_name='Tail #')),
                ('part_type', models.CharField(choices=[('Rotable', 'Rotable'), ('Tires', 'Tires'), ('AGS', 'AGS'), ('Consumables', 'Consumables'), ('Shelf-life', 'Shelf-life')], default='Rotable', max_length=20, verbose_name='Part-Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
