# Generated by Django 3.1.7 on 2021-03-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockfromshop',
            name='export_to_CSV',
        ),
        migrations.AddField(
            model_name='orderedpart',
            name='ticketed',
            field=models.BooleanField(blank=True, default='False', null=True),
        ),
    ]
