# Generated by Django 3.1.7 on 2021-06-24 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspector', to='mgmt.employees', verbose_name='Inspector:'),
        ),
    ]
