# Generated by Django 3.1.7 on 2021-03-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0002_auto_20210317_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedpart',
            name='recieve_part',
            field=models.BooleanField(blank=True, default='False', null=True),
        ),
    ]
