# Generated by Django 3.1.7 on 2021-06-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0002_auto_20210624_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partworkorders',
            name='issued_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
