# Generated by Django 3.1.7 on 2021-06-24 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0003_auto_20210624_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorders',
            name='tail_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mgmt.tailnumber', verbose_name='Tail #'),
        ),
    ]
