# Generated by Django 3.1.7 on 2021-03-19 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0004_auto_20210319_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('part_number', models.CharField(blank=True, max_length=50, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('order_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('issue_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('ipc_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('date_ordered', models.DateTimeField(auto_now=True)),
                ('ticketed', models.BooleanField(blank=True, default='False', null=True)),
                ('recieve_part', models.BooleanField(blank=True, default='False', null=True)),
                ('inspector', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('vendor', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_order_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bin_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ordered_by', models.CharField(choices=[('Terence', 'Terence'), ('James', 'James'), ('Denten', 'Denten'), ('Ivin', 'Ivin')], default='', max_length=20)),
                ('tail_number', models.CharField(choices=[('Stock', 'Stock'), ('N192WW', 'N192WW'), ('N193WW', 'N193WW'), ('N194WW', 'N194WW'), ('N195WW', 'N195WW'), ('N196WW', 'N196WW'), ('N197WW', 'N197WW'), ('N198WW', 'N198WW'), ('N190WW', 'N190WW'), ('N906WW', 'N906WW'), ('N3830S', 'N3830S'), ('N323WW', 'N323WW'), ('N491AK', 'N491AK'), ('N492AK', 'N492AK'), ('N725WW', 'N725WW'), ('N789WW', 'N789WW'), ('N921WW', 'N921WW')], default='AirFrame', max_length=20)),
                ('part_type', models.CharField(choices=[('Rotable', 'Rotable'), ('Tires', 'Tires'), ('AGS', 'AGS'), ('Consumables', 'Consumables'), ('N/A', 'N/A')], default='Rotable', max_length=20)),
                ('workorders', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mgmt.workorders')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderedPart',
        ),
        migrations.DeleteModel(
            name='StockfromShop',
        ),
    ]
