# Generated by Django 3.1.7 on 2021-06-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0005_auto_20210624_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='part_type',
            field=models.CharField(choices=[('Rotable', 'Rotable'), ('Tires', 'Tires'), ('AGS', 'AGS'), ('Consumables', 'Consumables'), ('Shelf-life', 'Shelf-life')], default='Rotable', max_length=20, verbose_name='Part-Type'),
        ),
    ]
