# Generated by Django 3.1.7 on 2021-03-25 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0005_auto_20210319_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='SRN',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='inspector',
            field=models.CharField(choices=[('Terence', 'Terence'), ('James', 'James'), ('Denten', 'Denten'), ('Ivin', 'Ivin')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='parts',
            name='workorders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mgmt.workorders'),
        ),
    ]
