# Generated by Django 3.1.7 on 2021-06-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0006_auto_20210624_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reorderitems',
            name='ordered_by',
        ),
        migrations.AlterField(
            model_name='reorderitems',
            name='tail_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
