# Generated by Django 3.1.7 on 2021-04-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0007_auto_20210401_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='cert_document',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
