# Generated by Django 3.1.7 on 2021-04-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0008_parts_cert_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='cert_document',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
