# Generated by Django 3.1.7 on 2021-07-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0008_auto_20210705_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
