# Generated by Django 3.1.7 on 2021-04-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0009_auto_20210402_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='cert_document',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
