# Generated by Django 3.1.7 on 2021-04-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0010_auto_20210402_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools_uncalibrated',
            name='recieved',
            field=models.DateField(auto_now=True),
        ),
    ]
