# Generated by Django 3.1.7 on 2021-07-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0010_auto_20210705_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorders',
            name='type_airframe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
