# Generated by Django 3.1.7 on 2021-07-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0011_workorders_type_airframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools_uncalibrated',
            name='recieved',
            field=models.DateField(auto_now=True),
        ),
    ]
