# Generated by Django 3.1.7 on 2021-04-05 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0012_auto_20210402_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parts',
            name='workorders',
        ),
        migrations.CreateModel(
            name='PartWorkOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mgmt.parts')),
                ('workorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mgmt.workorders')),
            ],
        ),
        migrations.AddField(
            model_name='parts',
            name='workorders',
            field=models.ManyToManyField(null=True, related_name='parts', through='mgmt.PartWorkOrders', to='mgmt.WorkOrders'),
        ),
    ]
