# Generated by Django 3.1.7 on 2021-04-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0013_auto_20210405_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='Historical',
            field=models.BooleanField(blank=True, default='False', null=True),
        ),
        migrations.AddField(
            model_name='parts',
            name='batch_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parts',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='part_type',
            field=models.CharField(choices=[('Rotable', 'Rotable'), ('Tires', 'Tires'), ('AGS', 'AGS'), ('Consumables', 'Consumables'), ('Shelf-life', 'Shelf-life')], default='Rotable', max_length=20),
        ),
    ]
