# Generated by Django 3.1.7 on 2021-04-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0014_auto_20210405_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorders',
            name='hours_at_open',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
