# Generated by Django 3.1.7 on 2021-07-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0014_auto_20210708_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='date_ordered',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
