# Generated by Django 3.1.7 on 2021-07-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0015_auto_20210708_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='date_ordered',
            field=models.DateField(auto_now=True),
        ),
    ]
