# Generated by Django 3.1.7 on 2021-04-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0015_workorders_hours_at_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorders',
            name='date_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
