# Generated by Django 3.1.7 on 2021-04-05 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0016_workorders_date_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partworkorders',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mgmt.parts'),
        ),
        migrations.AlterField(
            model_name='partworkorders',
            name='workorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mgmt.workorders'),
        ),
    ]
