# Generated by Django 3.1.7 on 2021-07-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0016_auto_20210708_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='breadth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parts',
            name='height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parts',
            name='length',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parts',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
