# Generated by Django 3.1.7 on 2021-04-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0017_auto_20210405_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='waybill',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
