# Generated by Django 3.1.7 on 2021-04-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0018_parts_waybill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='waybill',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
    ]
