# Generated by Django 3.1.7 on 2021-07-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0019_auto_20210708_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorders',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workorders',
            name='date_closed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
