# Generated by Django 3.1.7 on 2021-04-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0019_auto_20210406_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorders',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='cert_document',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Certification Document'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='purchase_order_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PurchaseOrder #'),
        ),
    ]
