# Generated by Django 3.1.7 on 2021-04-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0022_auto_20210408_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='date_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
