# Generated by Django 3.1.7 on 2021-07-19 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0024_auto_20210719_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='ordered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_by_history', to='mgmt.employees', verbose_name='Ordered by:'),
        ),
    ]
