# Generated by Django 3.1.7 on 2021-04-14 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0024_auto_20210410_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partworkorders',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mgmt.parts'),
        ),
        migrations.AlterField(
            model_name='partworkorders',
            name='workorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mgmt.workorders'),
        ),
    ]
