# Generated by Django 3.1.7 on 2021-04-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0025_auto_20210414_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='price',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
