# Generated by Django 3.1.7 on 2021-07-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0025_auto_20210719_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'Employees'},
        ),
    ]
