# Generated by Django 3.1.7 on 2021-04-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0026_parts_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
