# Generated by Django 3.1.7 on 2021-07-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0026_auto_20210719_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'Employee'},
        ),
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'verbose_name': 'Order History'},
        ),
        migrations.AlterModelOptions(
            name='parts',
            options={'verbose_name': 'Part'},
        ),
        migrations.AlterModelOptions(
            name='partworkorders',
            options={'verbose_name': 'Part Work Order (M2M)'},
        ),
        migrations.AlterModelOptions(
            name='reorderitems',
            options={'verbose_name': 'Re-Order Item'},
        ),
        migrations.AlterModelOptions(
            name='tools_calibrated',
            options={'verbose_name': 'Calibrated Tool'},
        ),
        migrations.AlterModelOptions(
            name='tools_uncalibrated',
            options={'verbose_name': 'UnCalibrated Tool'},
        ),
        migrations.AlterModelOptions(
            name='workorders',
            options={'verbose_name': 'Work Order'},
        ),
    ]
