# Generated by Django 3.1.7 on 2021-04-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0028_auto_20210415_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partworkorders',
            name='price',
        ),
        migrations.AddField(
            model_name='parts',
            name='issued_by',
            field=models.CharField(choices=[('Terence', 'Terence'), ('James', 'James'), ('Denten', 'Denten'), ('Ivin', 'Ivin')], default='', max_length=20, verbose_name='Issued by:'),
        ),
        migrations.AddField(
            model_name='partworkorders',
            name='issued_by',
            field=models.CharField(choices=[('Terence', 'Terence'), ('James', 'James'), ('Denten', 'Denten'), ('Ivin', 'Ivin')], default='', max_length=20, verbose_name='Issued by:'),
        ),
    ]
