# Generated by Django 3.1.7 on 2021-04-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0029_auto_20210415_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='partworkorders',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='parts',
            name='inspector',
            field=models.CharField(choices=[('Terence', 'Terence'), ('James', 'James'), ('Denten', 'Denten'), ('Ivin', 'Ivin'), ('Ester', 'Ester')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='parts',
            name='issued_by',
            field=models.CharField(choices=[('Terence', 'Terence'), ('James', 'James'), ('Denten', 'Denten'), ('Ivin', 'Ivin'), ('Ester', 'Ester')], default='', max_length=20, verbose_name='Issued by:'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='ordered_by',
            field=models.CharField(choices=[('Terence', 'Terence'), ('James', 'James'), ('Denten', 'Denten'), ('Ivin', 'Ivin'), ('Ester', 'Ester')], default='', max_length=20, verbose_name='Ordered by:'),
        ),
    ]
