# Generated by Django 3.1.7 on 2021-07-21 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0029_auto_20210721_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='ordered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderedShopList', to='mgmt.employees', verbose_name='Orderd By:'),
        ),
    ]
