# Generated by Django 3.1.7 on 2021-07-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0030_auto_20210721_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='part_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
