# Generated by Django 3.1.7 on 2021-07-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0032_shoppinglist_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='order_again',
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='re_order',
            field=models.BooleanField(blank=True, default='False', null=True),
        ),
    ]
