# Generated by Django 3.1.7 on 2021-04-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0032_parts_repaired'),
    ]

    operations = [
        migrations.AddField(
            model_name='partworkorders',
            name='cert_document',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Certification Document'),
        ),
    ]
