# Generated by Django 3.1.7 on 2021-04-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0033_partworkorders_cert_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='partworkorders',
            name='receivedRepair',
            field=models.BooleanField(blank=True, default='False', null=True),
        ),
    ]
