# Generated by Django 3.1.7 on 2021-07-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0034_auto_20210721_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='unitPrice',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
