# Generated by Django 3.1.7 on 2021-04-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0034_partworkorders_receivedrepair'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools_calibrated',
            name='removed_from',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
