# Generated by Django 3.1.7 on 2021-04-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0035_tools_calibrated_removed_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tools_calibrated',
            name='removed_from',
        ),
        migrations.AddField(
            model_name='partworkorders',
            name='removed_from',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
