# Generated by Django 3.1.7 on 2021-07-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0035_shoppinglist_unitprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='unitPrice',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
    ]
