# Generated by Django 3.1.7 on 2021-04-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0036_auto_20210419_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='partworkorders',
            name='removed_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
