# Generated by Django 3.1.7 on 2021-07-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0036_auto_20210722_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='issue_quantity',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
