# Generated by Django 3.1.7 on 2021-07-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0037_shoppinglist_issue_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='receive_quantity',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
