# Generated by Django 3.1.7 on 2021-04-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0037_partworkorders_removed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools_calibrated',
            name='calibration_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Certification Document'),
        ),
    ]
