# Generated by Django 3.1.7 on 2021-04-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0038_tools_calibrated_calibration_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='Quarentine',
            field=models.BooleanField(blank=True, default='False', null=True),
        ),
    ]
