# Generated by Django 3.1.7 on 2021-07-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0038_shoppinglist_receive_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='From',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
