# Generated by Django 3.1.7 on 2021-04-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0039_parts_quarentine'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='parts',
            name='condition',
            field=models.CharField(choices=[('NEW', 'NEW'), ('OH', 'OH'), ('AR', 'AR'), ('SV', 'SV'), ('REPAIRABLE', 'REPAIRABLE'), ('DAMAGED', 'DAMAGED'), ('INCORRECT-DOC', 'INCORRECT-DOC'), ('WRONG-PART', 'WRONG-PART')], default='NEW', max_length=20),
        ),
    ]
