# Generated by Django 3.1.7 on 2021-07-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0039_shoppinglist_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='ordered',
            field=models.BooleanField(blank=True, default='False', null=True),
        ),
    ]
