# Generated by Django 3.1.7 on 2021-07-23 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mgmt', '0040_shoppinglist_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools_Calibrated_issued',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('part_number', models.CharField(blank=True, max_length=50, null=True)),
                ('recieved', models.DateTimeField(auto_now=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('cert_no', models.CharField(blank=True, max_length=50, null=True)),
                ('calibration_certificate', models.ImageField(blank=True, null=True, upload_to='Cert-Tools', verbose_name='Certification Document')),
                ('range_no', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workorder_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mgmt.workorders')),
            ],
            options={
                'verbose_name': 'Calibrated Tool',
            },
        ),
    ]
