# Generated by Django 3.1.7 on 2021-04-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0041_auto_20210428_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='receive_quantity',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
