# Generated by Django 3.1.7 on 2021-07-26 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0041_tools_calibrated_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools_calibrated',
            name='issuedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mgmt.employees', verbose_name='Issued By:'),
        ),
        migrations.AddField(
            model_name='tools_calibrated',
            name='jobcard',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
