# Generated by Django 3.1.7 on 2021-04-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0042_parts_receive_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
