# Generated by Django 3.1.7 on 2021-04-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0043_auto_20210430_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='urlWayBill',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='waybill',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
