# Generated by Django 3.1.7 on 2021-07-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0043_auto_20210726_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tools_calibrated_issued',
            options={'verbose_name': 'Calibrated Issued Tool'},
        ),
        migrations.AddField(
            model_name='tools_calibrated_issued',
            name='calibrated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
