# Generated by Django 3.1.7 on 2021-05-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0046_tools_calibrated_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReorderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(choices=[('Rotable', 'Rotable'), ('Tires', 'Tires'), ('AGS', 'AGS'), ('Consumables', 'Consumables'), ('Shelf-life', 'Shelf-life')], default='Rotable', max_length=20, verbose_name='Part-Type')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('part_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ipc_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('tail_number', models.CharField(choices=[('Stock', 'Stock'), ('N192WW', 'N192WW'), ('N193WW', 'N193WW'), ('N194WW', 'N194WW'), ('N195WW', 'N195WW'), ('N196WW', 'N196WW'), ('N197WW', 'N197WW'), ('N198WW', 'N198WW'), ('N190WW', 'N190WW'), ('N906WW', 'N906WW'), ('N3830S', 'N3830S'), ('N323WW', 'N323WW'), ('N491AK', 'N491AK'), ('N492AK', 'N492AK'), ('N725WW', 'N725WW'), ('N789WW', 'N789WW'), ('N921WW', 'N921WW')], default='AirFrame', max_length=20, verbose_name='Tail #')),
                ('ordered_by', models.CharField(choices=[('Terence', 'Terence'), ('James', 'James'), ('Denten', 'Denten'), ('Ivin', 'Ivin'), ('Ester', 'Ester')], default='', max_length=20, verbose_name='Ordered by:')),
                ('date_ordered', models.DateTimeField(auto_now=True)),
                ('reorder_level', models.IntegerField(blank=True, default='0', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='parts',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='barcode-Parts'),
        ),
        migrations.AlterField(
            model_name='tools_calibrated',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='barcode-calibrated'),
        ),
    ]
