# Generated by Django 3.1.7 on 2021-05-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0049_reorderitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='reorderitems',
            name='order_quantity',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
