# Generated by Django 3.1.7 on 2021-05-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0050_reorderitems_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='exported',
            field=models.BooleanField(blank=True, default='False', null=True),
        ),
    ]
