# Generated by Django 3.1.7 on 2021-05-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0051_parts_exported'),
    ]

    operations = [
        migrations.AddField(
            model_name='reorderitems',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
